language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"


env:
  - DJANGO=django==1.6.8
  - DJANGO=django==1.7.1


install:
  - pip install -q $DJANGO
  - pip install -q flake8
  - pip install -q coveralls
  - python setup.py install

before_script:
  - make flake8

script:
  - make test

after_success:
  - make coveralls
